drop support for SCIP 1.2

diff --git a/ThirdParty/SCIP/configure b/ThirdParty/SCIP/configure
--- a/ThirdParty/SCIP/configure
+++ b/ThirdParty/SCIP/configure
@@ -22028,10 +22028,14 @@ echo $ECHO_N "checking SCIP version... $ECHO_C" >&6
   scipsubver=`awk '/define SCIP_SUBVERSION/ {print $3}' ${SCIPINCDIR}/scip/def.h`
   echo "$as_me:$LINENO: result: ${scipver}.${scipsubver}" >&5
 echo "${ECHO_T}${scipver}.${scipsubver}" >&6
-  if test x$scipver == x200 ; then
+  if test $scipver -lt 200 ; then
+    { { echo "$as_me:$LINENO: error: \"Incorrect SCIP version. This build system is made for SCIP >= 2.0.0\"" >&5
+echo "$as_me: error: \"Incorrect SCIP version. This build system is made for SCIP >= 2.0.0\"" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 
 
-if test 1 = 1; then
+if test $scipver != 200; then
   SCIPDEVVERSION_TRUE=
   SCIPDEVVERSION_FALSE='#'
 else
@@ -22039,16 +22043,7 @@ else
   SCIPDEVVERSION_FALSE=
 fi
 
-  elif test x$scipver != x120 ; then
-    { { echo "$as_me:$LINENO: error: \"Incorrect SCIP version. This build system is made for SCIP 120.x\"" >&5
-echo "$as_me: error: \"Incorrect SCIP version. This build system is made for SCIP 120.x\"" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
 
-#  if test x$minorver = x999 ; then
-#    CFLAGS=`echo $CFLAGS | sed -e 's/-pedantic-errors//'`
-#    CXXFLAGS=`echo $CXXFLAGS | sed -e 's/-pedantic-errors//'`
-#  else
   # SCIP uses long long that result in errors if -pedantic-errors is used
   # thus, we disable this warning
   case "$CC" in
