start of an OS interface

diff --git a/GAMSlinks/configure b/GAMSlinks/configure
--- a/GAMSlinks/configure
+++ b/GAMSlinks/configure
@@ -471,7 +471,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE EGREP LN_S CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX CXXLIBS F77 FFLAGS ac_ct_F77 FLIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS GAMSLINKSSRCDIR GAMSLINKSOBJDIR COIN_HAS_GAMSLINKS_TRUE COIN_HAS_GAMSLINKS_FALSE CGLSRCDIR CGLOBJDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CLPSRCDIR CLPOBJDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE DYLPSRCDIR DYLPOBJDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE SYMPHONYSRCDIR SYMPHONYOBJDIR COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE CBCSRCDIR CBCOBJDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE IPOPTSRCDIR IPOPTOBJDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE BONMINSRCDIR BONMINOBJDIR COIN_HAS_BONMIN_TRUE COIN_HAS_BONMIN_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE gamspath COIN_HAS_GAMSIO_TRUE COIN_HAS_GAMSIO_FALSE coin_has_gamsio GAMS_PATH GAMSIO_CPPFLAGS GAMSIO_LIBS SMAG_LIBS GAMSIO_CODE GAMSIO_IS_UNIX_TRUE GAMSIO_IS_UNIX_FALSE GAMSIO_IS_WINDOWS_TRUE GAMSIO_IS_WINDOWS_FALSE GAMSLINKS_BUILD_IPOPT_TRUE GAMSLINKS_BUILD_IPOPT_FALSE GAMSLINKS_BUILD_GAMSIO_TRUE GAMSLINKS_BUILD_GAMSIO_FALSE GAMSLINKS_BUILD_GLPK_TRUE GAMSLINKS_BUILD_GLPK_FALSE GAMSLINKS_BUILD_CBC_TRUE GAMSLINKS_BUILD_CBC_FALSE GAMSLINKS_BUILD_BONMIN_TRUE GAMSLINKS_BUILD_BONMIN_FALSE GAMSLINKS_BUILD_OSI_TRUE GAMSLINKS_BUILD_OSI_FALSE LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE EGREP LN_S CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX CXXLIBS F77 FFLAGS ac_ct_F77 FLIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS GAMSLINKSSRCDIR GAMSLINKSOBJDIR COIN_HAS_GAMSLINKS_TRUE COIN_HAS_GAMSLINKS_FALSE CGLSRCDIR CGLOBJDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CLPSRCDIR CLPOBJDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE DYLPSRCDIR DYLPOBJDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE SYMPHONYSRCDIR SYMPHONYOBJDIR COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE CBCSRCDIR CBCOBJDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE IPOPTSRCDIR IPOPTOBJDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE BONMINSRCDIR BONMINOBJDIR COIN_HAS_BONMIN_TRUE COIN_HAS_BONMIN_FALSE CPPADSRCDIR CPPADOBJDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE OSSRCDIR OSOBJDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE gamspath COIN_HAS_GAMSIO_TRUE COIN_HAS_GAMSIO_FALSE coin_has_gamsio GAMS_PATH GAMSIO_CPPFLAGS GAMSIO_LIBS SMAG_LIBS GAMSIO_CODE GAMSIO_IS_UNIX_TRUE GAMSIO_IS_UNIX_FALSE GAMSIO_IS_WINDOWS_TRUE GAMSIO_IS_WINDOWS_FALSE GAMSLINKS_BUILD_IPOPT_TRUE GAMSLINKS_BUILD_IPOPT_FALSE GAMSLINKS_BUILD_GAMSIO_TRUE GAMSLINKS_BUILD_GAMSIO_FALSE GAMSLINKS_BUILD_GLPK_TRUE GAMSLINKS_BUILD_GLPK_FALSE GAMSLINKS_BUILD_CBC_TRUE GAMSLINKS_BUILD_CBC_FALSE GAMSLINKS_BUILD_BONMIN_TRUE GAMSLINKS_BUILD_BONMIN_FALSE GAMSLINKS_BUILD_OSI_TRUE GAMSLINKS_BUILD_OSI_FALSE GAMSLINKS_BUILD_OS_TRUE GAMSLINKS_BUILD_OS_FALSE LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -21991,6 +21991,118 @@ fi
 echo "$as_me:$LINENO: result: $coin_has_bonmin" >&5
 echo "${ECHO_T}$coin_has_bonmin" >&6
 
+echo "$as_me:$LINENO: checking for COIN project cppad" >&5
+echo $ECHO_N "checking for COIN project cppad... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_cppad=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = cppad; then
+      coin_has_cppad=skipping
+    fi
+  done
+fi
+
+if test $coin_has_cppad != skipping; then
+  if test $PACKAGE_TARNAME = cppad; then
+    coin_has_cppad=.
+  else
+    if test -d $srcdir/../cppad; then
+      coin_has_cppad=../cppad
+    fi
+  fi
+fi
+
+if test $coin_has_cppad != unavailable &&
+   test $coin_has_cppad != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_CPPAD 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  CPPADSRCDIR=`cd $srcdir/$coin_has_cppad; pwd`
+
+  CPPADOBJDIR=`pwd`/$coin_has_cppad
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_cppad != unavailable &&
+                test $coin_has_cppad != skipping; then
+  COIN_HAS_CPPAD_TRUE=
+  COIN_HAS_CPPAD_FALSE='#'
+else
+  COIN_HAS_CPPAD_TRUE='#'
+  COIN_HAS_CPPAD_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_cppad" >&5
+echo "${ECHO_T}$coin_has_cppad" >&6
+
+echo "$as_me:$LINENO: checking for COIN project OS" >&5
+echo $ECHO_N "checking for COIN project OS... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_os=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = OS; then
+      coin_has_os=skipping
+    fi
+  done
+fi
+
+if test $coin_has_os != skipping; then
+  if test $PACKAGE_TARNAME = os; then
+    coin_has_os=.
+  else
+    if test -d $srcdir/../OS; then
+      coin_has_os=../OS
+    fi
+  fi
+fi
+
+if test $coin_has_os != unavailable &&
+   test $coin_has_os != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_OS 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  OSSRCDIR=`cd $srcdir/$coin_has_os; pwd`
+
+  OSOBJDIR=`pwd`/$coin_has_os
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_os != unavailable &&
+                test $coin_has_os != skipping; then
+  COIN_HAS_OS_TRUE=
+  COIN_HAS_OS_FALSE='#'
+else
+  COIN_HAS_OS_TRUE='#'
+  COIN_HAS_OS_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_os" >&5
+echo "${ECHO_T}$coin_has_os" >&6
+
 
 ############################################################################
 ############################################################################
@@ -25161,6 +25273,20 @@ else
 fi
 
 
+
+
+if
+   test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
+   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
+   test "x$coin_has_cppad" != xunavailable && test "x$coin_has_cppad" != xskipping ; then
+  GAMSLINKS_BUILD_OS_TRUE=
+  GAMSLINKS_BUILD_OS_FALSE='#'
+else
+  GAMSLINKS_BUILD_OS_TRUE='#'
+  GAMSLINKS_BUILD_OS_FALSE=
+fi
+
+
 ##############################################################################
 #                VPATH links for GAMS installation files                     #
 ##############################################################################
@@ -25294,6 +25420,26 @@ if test $coin_vpath_config = yes; then
 fi
 
 
+if test $coin_vpath_config = yes; then
+  coin_vpath_link_files="$coin_vpath_link_files src/OS/gmsos_us.run"
+fi
+
+
+if test $coin_vpath_config = yes; then
+  coin_vpath_link_files="$coin_vpath_link_files src/OS/gmsos_nt.cmd"
+fi
+
+
+if test $coin_vpath_config = yes; then
+  coin_vpath_link_files="$coin_vpath_link_files src/OS/install/gmsos_un.dat"
+fi
+
+
+if test $coin_vpath_config = yes; then
+  coin_vpath_link_files="$coin_vpath_link_files src/OS/install/gmsos_nt.dat"
+fi
+
+
 ############
 # END PART #
 ############
@@ -25305,7 +25451,7 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-                                                                                                              ac_config_files="$ac_config_files Makefile src/Makefile src/GamsIO/Makefile src/GamsIO/gamsio_addlibs.txt src/Cbc/Makefile src/Glpk/Makefile src/Osi/Makefile src/Ipopt/Makefile src/Bonmin/Makefile test/Makefile test/run_tests"
+                                                                                                                        ac_config_files="$ac_config_files Makefile src/Makefile src/GamsIO/Makefile src/GamsIO/gamsio_addlibs.txt src/Cbc/Makefile src/Glpk/Makefile src/Osi/Makefile src/Ipopt/Makefile src/Bonmin/Makefile src/OS/Makefile test/Makefile test/run_tests"
 
 
           ac_config_headers="$ac_config_headers inc/config_gamslinks.h"
@@ -25578,6 +25724,20 @@ echo "$as_me: error: conditional \"COIN_HAS_BONMIN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${COIN_HAS_CPPAD_TRUE}" && test -z "${COIN_HAS_CPPAD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_CPPAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_CPPAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_OS_TRUE}" && test -z "${COIN_HAS_OS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_OS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_OS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${COIN_HAS_GLPK_TRUE}" && test -z "${COIN_HAS_GLPK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_GLPK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -25659,6 +25819,13 @@ if test -z "${GAMSLINKS_BUILD_OSI_TRUE}" && test -z "${GAMSLINKS_BUILD_OSI_FALSE
   { { echo "$as_me:$LINENO: error: conditional \"GAMSLINKS_BUILD_OSI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"GAMSLINKS_BUILD_OSI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${GAMSLINKS_BUILD_OS_TRUE}" && test -z "${GAMSLINKS_BUILD_OS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GAMSLINKS_BUILD_OS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"GAMSLINKS_BUILD_OS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -26115,6 +26282,7 @@ do
   "src/Osi/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Osi/Makefile" ;;
   "src/Ipopt/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Ipopt/Makefile" ;;
   "src/Bonmin/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Bonmin/Makefile" ;;
+  "src/OS/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/OS/Makefile" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "test/run_tests" ) CONFIG_FILES="$CONFIG_FILES test/run_tests" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
@@ -26349,6 +26517,14 @@ s,@BONMINSRCDIR@,$BONMINSRCDIR,;t t
 s,@BONMINOBJDIR@,$BONMINOBJDIR,;t t
 s,@COIN_HAS_BONMIN_TRUE@,$COIN_HAS_BONMIN_TRUE,;t t
 s,@COIN_HAS_BONMIN_FALSE@,$COIN_HAS_BONMIN_FALSE,;t t
+s,@CPPADSRCDIR@,$CPPADSRCDIR,;t t
+s,@CPPADOBJDIR@,$CPPADOBJDIR,;t t
+s,@COIN_HAS_CPPAD_TRUE@,$COIN_HAS_CPPAD_TRUE,;t t
+s,@COIN_HAS_CPPAD_FALSE@,$COIN_HAS_CPPAD_FALSE,;t t
+s,@OSSRCDIR@,$OSSRCDIR,;t t
+s,@OSOBJDIR@,$OSOBJDIR,;t t
+s,@COIN_HAS_OS_TRUE@,$COIN_HAS_OS_TRUE,;t t
+s,@COIN_HAS_OS_FALSE@,$COIN_HAS_OS_FALSE,;t t
 s,@GLPKINCDIR@,$GLPKINCDIR,;t t
 s,@GLPKLIB@,$GLPKLIB,;t t
 s,@COIN_HAS_GLPK_TRUE@,$COIN_HAS_GLPK_TRUE,;t t
@@ -26380,6 +26556,8 @@ s,@GAMSLINKS_BUILD_BONMIN_TRUE@,$GAMSLINKS_BUILD_BONMIN_TRUE,;t t
 s,@GAMSLINKS_BUILD_BONMIN_FALSE@,$GAMSLINKS_BUILD_BONMIN_FALSE,;t t
 s,@GAMSLINKS_BUILD_OSI_TRUE@,$GAMSLINKS_BUILD_OSI_TRUE,;t t
 s,@GAMSLINKS_BUILD_OSI_FALSE@,$GAMSLINKS_BUILD_OSI_FALSE,;t t
+s,@GAMSLINKS_BUILD_OS_TRUE@,$GAMSLINKS_BUILD_OS_TRUE,;t t
+s,@GAMSLINKS_BUILD_OS_FALSE@,$GAMSLINKS_BUILD_OS_FALSE,;t t
 s,@LIBEXT@,$LIBEXT,;t t
 s,@VPATH_DISTCLEANFILES@,$VPATH_DISTCLEANFILES,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
