add gams-install target and get.GAMSIO, have tests recognize nonexisting or skipped projects

diff --git a/GAMSlinks/Makefile.am b/GAMSlinks/Makefile.am
--- a/GAMSlinks/Makefile.am
+++ b/GAMSlinks/Makefile.am
@@ -27,7 +27,18 @@ test: all
 
 unitTest: test
 
-.PHONY: test unitTest
+if COIN_HAS_GAMSSYSTEM
+gams-install: install
+	echo "Installation of solvers in GAMS distribution at @GAMS_PATH@."
+	cp $(DESTDIR)$(bindir)/gms*_.zip @GAMS_PATH@
+	cd @GAMS_PATH@; gamsinst -a
+else
+gams-install: 
+	echo "Installation of solvers in GAMS distribution fails because path of GAMS system not known."
+	exit 1
+endif
+
+.PHONY: test unitTest gams-install
 
 # Stuff to clean up
 clean-local:
diff --git a/GAMSlinks/configure b/GAMSlinks/configure
--- a/GAMSlinks/configure
+++ b/GAMSlinks/configure
@@ -471,7 +471,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE EGREP LN_S CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX CXXLIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS GAMSLINKSSRCDIR GAMSLINKSOBJDIR COIN_HAS_GAMSLINKS_TRUE COIN_HAS_GAMSLINKS_FALSE CGLSRCDIR CGLOBJDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CLPSRCDIR CLPOBJDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE DYLPSRCDIR DYLPOBJDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE SYMPHONYSRCDIR SYMPHONYOBJDIR COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE CBCSRCDIR CBCOBJDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE IPOPTSRCDIR IPOPTOBJDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE BONMINSRCDIR BONMINOBJDIR COIN_HAS_BONMIN_TRUE COIN_HAS_BONMIN_FALSE CPPADSRCDIR CPPADOBJDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE OSSRCDIR OSOBJDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE gamspath COIN_HAS_GAMSIO_TRUE COIN_HAS_GAMSIO_FALSE coin_has_gamsio GAMS_PATH GAMSIO_CPPFLAGS GAMSIO_ADDLIBS GAMSIO_LIBS SMAG_LIBS GAMSIO_CODE GAMSIO_IS_UNIX_TRUE GAMSIO_IS_UNIX_FALSE GAMSIO_IS_WINDOWS_TRUE GAMSIO_IS_WINDOWS_FALSE COIN_OS_SOLVER_TRUE COIN_OS_SOLVER_FALSE coin_build_ipopt coin_build_glpk coin_build_cbc coin_build_bonmin coin_build_osi GAMSLINKS_BUILD_IPOPT_TRUE GAMSLINKS_BUILD_IPOPT_FALSE GAMSLINKS_BUILD_GAMSIO_TRUE GAMSLINKS_BUILD_GAMSIO_FALSE GAMSLINKS_BUILD_GLPK_TRUE GAMSLINKS_BUILD_GLPK_FALSE GAMSLINKS_BUILD_CBC_TRUE GAMSLINKS_BUILD_CBC_FALSE GAMSLINKS_BUILD_BONMIN_TRUE GAMSLINKS_BUILD_BONMIN_FALSE GAMSLINKS_BUILD_OSI_TRUE GAMSLINKS_BUILD_OSI_FALSE GAMSLINKS_BUILD_OS_TRUE GAMSLINKS_BUILD_OS_FALSE LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE EGREP LN_S CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX CXXLIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS GAMSLINKSSRCDIR GAMSLINKSOBJDIR COIN_HAS_GAMSLINKS_TRUE COIN_HAS_GAMSLINKS_FALSE CGLSRCDIR CGLOBJDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CLPSRCDIR CLPOBJDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE DYLPSRCDIR DYLPOBJDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE SYMPHONYSRCDIR SYMPHONYOBJDIR COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE CBCSRCDIR CBCOBJDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE IPOPTSRCDIR IPOPTOBJDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE BONMINSRCDIR BONMINOBJDIR COIN_HAS_BONMIN_TRUE COIN_HAS_BONMIN_FALSE CPPADSRCDIR CPPADOBJDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE OSSRCDIR OSOBJDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE gamspath COIN_HAS_GAMSSYSTEM_TRUE COIN_HAS_GAMSSYSTEM_FALSE COIN_HAS_GAMSIO_TRUE COIN_HAS_GAMSIO_FALSE coin_has_gamsio GAMS_PATH GAMSIO_CPPFLAGS GAMSIO_ADDLIBS GAMSIO_LIBS SMAG_LIBS GAMSIO_CODE GAMSIO_IS_UNIX_TRUE GAMSIO_IS_UNIX_FALSE GAMSIO_IS_WINDOWS_TRUE GAMSIO_IS_WINDOWS_FALSE COIN_OS_SOLVER_TRUE COIN_OS_SOLVER_FALSE gamslinks_build_ipopt GAMSLINKS_BUILD_IPOPT_TRUE GAMSLINKS_BUILD_IPOPT_FALSE GAMSLINKS_BUILD_GAMSIO_TRUE GAMSLINKS_BUILD_GAMSIO_FALSE gamslinks_build_glpk GAMSLINKS_BUILD_GLPK_TRUE GAMSLINKS_BUILD_GLPK_FALSE gamslinks_build_cbc GAMSLINKS_BUILD_CBC_TRUE GAMSLINKS_BUILD_CBC_FALSE gamslinks_build_bonmin GAMSLINKS_BUILD_BONMIN_TRUE GAMSLINKS_BUILD_BONMIN_FALSE gamslinks_build_osi GAMSLINKS_BUILD_OSI_TRUE GAMSLINKS_BUILD_OSI_FALSE GAMSLINKS_BUILD_OS_TRUE GAMSLINKS_BUILD_OS_FALSE LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -23891,6 +23891,16 @@ fi;
 #	AC_MSG_RESULT([no GAMS system available])
 #fi
 
+
+if test $GAMS_PATH != UNAVAILABLE; then
+  COIN_HAS_GAMSSYSTEM_TRUE=
+  COIN_HAS_GAMSSYSTEM_FALSE='#'
+else
+  COIN_HAS_GAMSSYSTEM_TRUE='#'
+  COIN_HAS_GAMSSYSTEM_FALSE=
+fi
+
+
 ####################
 # GAMS I/O LIBRARY #
 ####################
@@ -24264,78 +24274,14 @@ echo "${ECHO_T}$os_solver" >&6
 ##################################################
 
 if test "x$coin_has_ipopt" != "xunavailable" && test "x$coin_has_ipopt" != "xskipping"; then
-  coin_build_ipopt=1
+  gamslinks_build_ipopt=1
 else
-  coin_build_ipopt=0
-fi
-
-
-if test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != skipping ; then
-  coin_build_gamsio=1
-else
-  coin_build_gamsio=0
-fi
-
-if test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
-   test "x$coin_has_glpk" = xtrue ; then
-  coin_build_glpk=1
-else
-  coin_build_glpk=0
-fi
-
-
-if test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
-   test "x$coin_has_clp" != xunavailable && test "x$coin_has_clp" != skipping &&
-   test "x$coin_has_cgl" != xunavailable && test "x$coin_has_cgl" != skipping &&
-   test "x$coin_has_cbc" != xunavailable && test "x$coin_has_cbc" != skipping ; then
-  coin_build_cbc=1
-else
-  coin_build_cbc=0
-fi
-
-
-if test "x$coin_has_ipopt" != xunavailable && test "x$coin_has_ipopt" != xskipping &&
-   test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
-   test "x$coin_has_cgl" != xunavailable && test "x$coin_has_cgl" != xskipping &&
-   test "x$coin_has_cbc" != xunavailable && test "x$coin_has_cbc" != xskipping &&
-   test "x$coin_has_clp" != xunavailable && test "x$coin_has_clp" != xskipping &&
-   test "x$coin_has_bonmin" != xunavailable && test "x$coin_has_bonmin" != xskipping ; then
-  coin_build_bonmin=1
-else
-  coin_build_bonmin=0
-fi
-
-
-if test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
-   ( ( test "x$coin_has_dylp" != xunavailable && test "x$coin_has_dylp" != xskipping ) ||
-     ( test "x$coin_has_symphony" != xunavailable && test "x$coin_has_symphony" != xskipping ) ||
-     ( test "x$coin_has_vol" != xunavailable && test "x$coin_has_vol" != skipping )
-   ) ; then
-  coin_build_osi=1
-else
-  coin_build_osi=0
-fi
-
-
-if test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_os" != xunavailable && test "x$coin_has_os" != xskipping &&
-   test "x$coin_has_cppad" != xunavailable && test "x$coin_has_cppad" != xskipping ; then
-  coin_build_os=1
-else
-  coin_build_os=0
+  gamslinks_build_ipopt=0
 fi
 
 
 
-
-
-if
-   test "x$coin_has_ipopt" != "xunavailable" && test "x$coin_has_ipopt" != "xskipping" ; then
+if test $gamslinks_build_ipopt == 1; then
   GAMSLINKS_BUILD_IPOPT_TRUE=
   GAMSLINKS_BUILD_IPOPT_FALSE='#'
 else
@@ -24344,11 +24290,15 @@ else
 fi
 
 
+if test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
+   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != skipping ; then
+  gamslinks_build_gamsio=1
+else
+  gamslinks_build_gamsio=0
+fi
 
 
-if
-   test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != skipping  ; then
+if test $gamslinks_build_gamsio == 1; then
   GAMSLINKS_BUILD_GAMSIO_TRUE=
   GAMSLINKS_BUILD_GAMSIO_FALSE='#'
 else
@@ -24357,12 +24307,15 @@ else
 fi
 
 
+if test $gamslinks_build_gamsio && test "x$coin_has_glpk" = xtrue ; then
+  gamslinks_build_glpk=1
+else
+  gamslinks_build_glpk=0
+fi
 
 
-if
-   test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
-   test "x$coin_has_glpk" = xtrue ; then
+
+if test $gamslinks_build_glpk == 1; then
   GAMSLINKS_BUILD_GLPK_TRUE=
   GAMSLINKS_BUILD_GLPK_FALSE='#'
 else
@@ -24371,14 +24324,18 @@ else
 fi
 
 
-
-
-if
-   test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
+if test $gamslinks_build_gamsio &&
    test "x$coin_has_clp" != xunavailable && test "x$coin_has_clp" != skipping &&
    test "x$coin_has_cgl" != xunavailable && test "x$coin_has_cgl" != skipping &&
-   test "x$coin_has_cbc" != xunavailable && test "x$coin_has_cbc" != skipping  ; then
+   test "x$coin_has_cbc" != xunavailable && test "x$coin_has_cbc" != skipping ; then
+  gamslinks_build_cbc=1
+else
+  gamslinks_build_cbc=0
+fi
+
+
+
+if test $gamslinks_build_cbc == 1; then
   GAMSLINKS_BUILD_CBC_TRUE=
   GAMSLINKS_BUILD_CBC_FALSE='#'
 else
@@ -24388,15 +24345,16 @@ fi
 
 
 
-
-if
-   test "x$coin_has_ipopt" != xunavailable && test "x$coin_has_ipopt" != xskipping &&
-   test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
-   test "x$coin_has_cgl" != xunavailable && test "x$coin_has_cgl" != xskipping &&
-   test "x$coin_has_cbc" != xunavailable && test "x$coin_has_cbc" != xskipping &&
-   test "x$coin_has_clp" != xunavailable && test "x$coin_has_clp" != xskipping &&
+if test $gamslinks_build_cbc && test $gamslinks_build_ipopt &&
    test "x$coin_has_bonmin" != xunavailable && test "x$coin_has_bonmin" != xskipping ; then
+  gamslinks_build_bonmin=1
+else
+  gamslinks_build_bonmin=0
+fi
+
+
+
+if test $gamslinks_build_bonmin == 1; then
   GAMSLINKS_BUILD_BONMIN_TRUE=
   GAMSLINKS_BUILD_BONMIN_FALSE='#'
 else
@@ -24405,15 +24363,19 @@ else
 fi
 
 
-
-
-if
-   test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
-   test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
+if test $gamslinks_build_gamsio &&
    ( ( test "x$coin_has_dylp" != xunavailable && test "x$coin_has_dylp" != xskipping ) ||
      ( test "x$coin_has_symphony" != xunavailable && test "x$coin_has_symphony" != xskipping ) ||
      ( test "x$coin_has_vol" != xunavailable && test "x$coin_has_vol" != skipping )
    ) ; then
+  gamslinks_build_osi=1
+else
+  gamslinks_build_osi=0
+fi
+
+
+
+if test $gamslinks_build_osi == 1; then
   GAMSLINKS_BUILD_OSI_TRUE=
   GAMSLINKS_BUILD_OSI_FALSE='#'
 else
@@ -24422,12 +24384,16 @@ else
 fi
 
 
-
-
-if
-   test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
+if test "x$coin_has_coinutils" != xunavailable && test "x$coin_has_coinutils" != xskipping &&
    test "x$coin_has_os" != xunavailable && test "x$coin_has_os" != xskipping &&
    test "x$coin_has_cppad" != xunavailable && test "x$coin_has_cppad" != xskipping ; then
+  gamslinks_build_os=1
+else
+  gamslinks_build_os=0
+fi
+
+
+if test $gamslinks_build_os == 1; then
   GAMSLINKS_BUILD_OS_TRUE=
   GAMSLINKS_BUILD_OS_FALSE='#'
 else
@@ -24435,7 +24401,6 @@ else
   GAMSLINKS_BUILD_OS_FALSE=
 fi
 
-#test "x$coin_has_osi" != xunavailable && test "x$coin_has_osi" != xskipping &&
 
 ##############################################################################
 #                VPATH links for GAMS installation files                     #
@@ -24911,6 +24876,13 @@ if test -z "${COIN_BUILD_GLPK_TRUE}" && test -z "${COIN_BUILD_GLPK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COIN_BUILD_GLPK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"COIN_BUILD_GLPK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_GAMSSYSTEM_TRUE}" && test -z "${COIN_HAS_GAMSSYSTEM_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_GAMSSYSTEM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_GAMSSYSTEM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -25694,6 +25666,8 @@ s,@COIN_HAS_GLPK_FALSE@,$COIN_HAS_GLPK_FALSE,;t t
 s,@COIN_BUILD_GLPK_TRUE@,$COIN_BUILD_GLPK_TRUE,;t t
 s,@COIN_BUILD_GLPK_FALSE@,$COIN_BUILD_GLPK_FALSE,;t t
 s,@gamspath@,$gamspath,;t t
+s,@COIN_HAS_GAMSSYSTEM_TRUE@,$COIN_HAS_GAMSSYSTEM_TRUE,;t t
+s,@COIN_HAS_GAMSSYSTEM_FALSE@,$COIN_HAS_GAMSSYSTEM_FALSE,;t t
 s,@COIN_HAS_GAMSIO_TRUE@,$COIN_HAS_GAMSIO_TRUE,;t t
 s,@COIN_HAS_GAMSIO_FALSE@,$COIN_HAS_GAMSIO_FALSE,;t t
 s,@coin_has_gamsio@,$coin_has_gamsio,;t t
@@ -25709,21 +25683,21 @@ s,@GAMSIO_IS_WINDOWS_TRUE@,$GAMSIO_IS_WINDOWS_TRUE,;t t
 s,@GAMSIO_IS_WINDOWS_FALSE@,$GAMSIO_IS_WINDOWS_FALSE,;t t
 s,@COIN_OS_SOLVER_TRUE@,$COIN_OS_SOLVER_TRUE,;t t
 s,@COIN_OS_SOLVER_FALSE@,$COIN_OS_SOLVER_FALSE,;t t
-s,@coin_build_ipopt@,$coin_build_ipopt,;t t
-s,@coin_build_glpk@,$coin_build_glpk,;t t
-s,@coin_build_cbc@,$coin_build_cbc,;t t
-s,@coin_build_bonmin@,$coin_build_bonmin,;t t
-s,@coin_build_osi@,$coin_build_osi,;t t
+s,@gamslinks_build_ipopt@,$gamslinks_build_ipopt,;t t
 s,@GAMSLINKS_BUILD_IPOPT_TRUE@,$GAMSLINKS_BUILD_IPOPT_TRUE,;t t
 s,@GAMSLINKS_BUILD_IPOPT_FALSE@,$GAMSLINKS_BUILD_IPOPT_FALSE,;t t
 s,@GAMSLINKS_BUILD_GAMSIO_TRUE@,$GAMSLINKS_BUILD_GAMSIO_TRUE,;t t
 s,@GAMSLINKS_BUILD_GAMSIO_FALSE@,$GAMSLINKS_BUILD_GAMSIO_FALSE,;t t
+s,@gamslinks_build_glpk@,$gamslinks_build_glpk,;t t
 s,@GAMSLINKS_BUILD_GLPK_TRUE@,$GAMSLINKS_BUILD_GLPK_TRUE,;t t
 s,@GAMSLINKS_BUILD_GLPK_FALSE@,$GAMSLINKS_BUILD_GLPK_FALSE,;t t
+s,@gamslinks_build_cbc@,$gamslinks_build_cbc,;t t
 s,@GAMSLINKS_BUILD_CBC_TRUE@,$GAMSLINKS_BUILD_CBC_TRUE,;t t
 s,@GAMSLINKS_BUILD_CBC_FALSE@,$GAMSLINKS_BUILD_CBC_FALSE,;t t
+s,@gamslinks_build_bonmin@,$gamslinks_build_bonmin,;t t
 s,@GAMSLINKS_BUILD_BONMIN_TRUE@,$GAMSLINKS_BUILD_BONMIN_TRUE,;t t
 s,@GAMSLINKS_BUILD_BONMIN_FALSE@,$GAMSLINKS_BUILD_BONMIN_FALSE,;t t
+s,@gamslinks_build_osi@,$gamslinks_build_osi,;t t
 s,@GAMSLINKS_BUILD_OSI_TRUE@,$GAMSLINKS_BUILD_OSI_TRUE,;t t
 s,@GAMSLINKS_BUILD_OSI_FALSE@,$GAMSLINKS_BUILD_OSI_FALSE,;t t
 s,@GAMSLINKS_BUILD_OS_TRUE@,$GAMSLINKS_BUILD_OS_TRUE,;t t
diff --git a/GAMSlinks/test/run_tests.in b/GAMSlinks/test/run_tests.in
--- a/GAMSlinks/test/run_tests.in
+++ b/GAMSlinks/test/run_tests.in
@@ -22,22 +22,25 @@ fi
 echo Getting quality tests driver from GAMS test library...
 $gamspath/testlib quality
 
-#TODO: check whether quality.gms is there now
+if test ! -e quality.gms ; then
+  echo "Failed to obtain quality.gms from GAMS test library."
+  exit 1
+fi
 
 solvers=
 skiplist=
-nrtests=0
 declare -a testlist
-if test @coin_build_ipopt@ ; then
+if test @gamslinks_build_ipopt@ == 1 ; then
   solvers="$solvers , Ipopt"
   skiplist="$skiplist skip('Ipopt','lp03')=yes;"
   skiplist="$skiplist skip('Ipopt','sl4lp03')=yes;"
   skiplist="$skiplist skip('Ipopt','lp10')=yes;"
   skiplist="$skiplist skip('Ipopt','sl4lp10')=yes;"
+  testlist[${#testlist[@]}]="--solver ipopt --suite lp"
   testlist[${#testlist[@]}]="--solver ipopt --suite nlp"
   testlist[${#testlist[@]}]="--solver ipopt --suite qcp"
 fi
-if test @coin_build_glpk@ ; then
+if test @gamslinks_build_glpk@ == 1 ; then
   solvers="$solvers , Glpk"
   skiplist="$skiplist skip('Glpk','sos1a')=yes;"
   skiplist="$skiplist skip('Glpk','sl4sos1a')=yes;"
@@ -46,14 +49,14 @@ if test @coin_build_glpk@ ; then
   testlist[${#testlist[@]}]="--solver glpk --suite lp"
   testlist[${#testlist[@]}]="--solver glpk --suite mip"
 fi
-if test @coin_build_cbc@ ; then
+if test @gamslinks_build_cbc@ == 1 ; then
   solvers="$solvers , Cbc"
 #  skiplist="$skiplist skip('Cbc','semicon1')=yes;"
 #  skiplist="$skiplist skip('Cbc','sl4scon1')=yes;"
   testlist[${#testlist[@]}]="--solver cbc --suite lp"
   testlist[${#testlist[@]}]="--solver cbc --suite mip"
 fi
-if test @coin_build_bonmin@ ; then
+if test @gamslinks_build_bonmin@ == 1 ; then
   solvers="$solvers , Bonmin"
   skiplist="$skiplist skip('Bonmin','sos1a')=yes;"
   skiplist="$skiplist skip('Bonmin','sl4sos1a')=yes;"
@@ -76,11 +79,14 @@ sed -e "/master set of solvers/s/\/;\$/$solvers \/;/" \
     quality.gms > quality_coin.gms
 echo ""
 
+#remove all log or failure files
+rm -f quality_test_*.log failures_qa*.gms
+
 #indicates whether there was a failed test, also return code of this script
 testfailed=0
 
 for (( i=0 ; i<${#testlist[@]} ; i++ )) ; do
-  echo "Run quality test driver with options " ${testlist[$i]} 
+  echo "Run quality test $(($i+1)) of ${#testlist[@]} with options " ${testlist[$i]} 
 
 	if $gamspath/gams quality_coin.gms ${testlist[$i]} lo=2 logfile=quality_test_$i.log ; then
 		echo "Test " ${testlist[$i]} " passed."
